### ISSUE TITLE
Coop load time reduction

### ISSUE THREAD

**Issue by betsruner** [ChaosInitiative/Portal-2-Community-Edition#123]
If it's possible in coop have both the players loading at the same time as opposed to orange loading in after blue.

**Comment by distributivgesetz** [comment]
Unless there is some kind of way to moderately speed up server start, asset precaching etc. for blue, I don't think there is a way to optimize loading to a point where both parties can load in at the same time.

**Comment by JJL772** [comment]
The host is spinning up a server, so the client cannot connect before the host loads in. Fixing this would require a pretty huge refactor to the entire engine. Best thing we could do is improve load times as best as possible, and maybe optimize the map loader. 

Closing this for now because we have an internal ticket for engine optimization
