### ISSUE TITLE
Janky Lift Clipping in GLaDOS wake-up sequence.

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#234]

**Comment by Konclan** [comment]
This issue is very non descriptive. What lift, why is it Janky?

**Comment by distributivgesetz** [comment]
I think the breaker lift is meant here (since that's the only lift in `sp_a1_wakeup`)...
The lift is indeed very janky similarly to the laggy wakeup animation in the container ride level.
The console is also spammed with the text `Ignoring/Fixing player blocking train!`. 
The second error message is what is presumably causing the "laggy" ascent, because the game does not account for the player moving upwards on a `func_tracktrain` and therefore the player gets stuck, and the game attempts to unstuck the player by teleporting the player back ontop of the train...

**Comment by JJL772** [comment]
I think this was fixed at some point. More descriptive titles would be great in the future, but then again this is a year old issue lol
