### ISSUE TITLE
Hammer Editing Map Properties Selects Entire Map

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#247]
This can cause a lot of lag and sometimes crash hammer

**Comment by Luke18033** [comment]
It's selecting `worldspawn`, which seems like it should only select world brushes...

**Comment by distributivgesetz** [comment]
When examining a .vmf file in a text editor, you might also think that it should only select world brushes, since they fall into the `world "category"` alongside `worldspawn`, but not entities...

However, I can't remember any case where Hammer ever freezes while selecting everything, let alone crash because of it...
This needs more proof to show that this is a problem.

**Comment by SpyceTewan** [comment]
I don't see this as a problem..

**Comment by L89David** [comment]
It can be a problem in bigger maps... Selecting everything does cause an insane amount of lag if there are a lot of objects with helpers. Would be too hard to make it so when you open the map properties nothing shows visually selected? (it could be internally selected)
