### ISSUE TITLE
Add customization options to point_worldtext

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#36]
A simple entity to display floating text in a map

**Comment by Fennecai** [comment]
kindof there already? env_message i think its called, or point_message. but that's basically a developer only thing and it doesn't look that great...it'd be great to make this usable as nice-looking colorable text, and have it optional to always face the player or not, so that it can be used on signs and screens and stuff

**Comment by Luke18033** [comment]
Doesn't CS:GO have a `point_worldtext` entity that does exactly this?

**Comment by distributivgesetz** [comment]
> Doesn't CS:GO have a `point_worldtext` entity that does exactly this?

Yes, but the default font seems to be buggy, also there is next to no customization for the font and the text outline, this could be added for bonus customizability.

![fdsafdsa](https://user-images.githubusercontent.com/47710522/85917600-cda68b00-b85b-11ea-8f0a-f9ab1006d293.png)

**Comment by Luke18033** [comment]
Ah, I've only used the HL:A version (which provides more customization and doesn't have those issues).

**Comment by CitadelCore** [comment]
We should be able to customise point_worldtext.

**Comment by SpyceTewan** [comment]
Will add font customization. The outline is just part of the font

**Comment by SpyceTewan** [comment]
Added `font` keyvalue
