### ISSUE TITLE
Portal color cvars don't work when executed through game.cfg

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#593]
### Describe the bug
The console reports `Can't use command cl_portal_sp_primary_color in multiplayer.` It seems like the game is considered to be in multiplayer while loading a map? I haven't played multiplayer at all since starting the game.

As I predicted, this makes it impossible to have global custom portal colors. *Sigh.*

### To Reproduce
1. Create `game.cfg` and add portal color cvars to it:
```
cl_portal_alternate_colors 1
cl_portal_sp_primary_color 0 165 254
cl_portal_sp_secondary_color 0 182 15
```
2. Load map
3. :x: Portal colors don't change, console reports `Can't use command cl_portal_sp_primary_color in multiplayer.`

### Expected behavior
Portal color cvars should work when executed from `game.cfg`.

### Operating System (Optional: Only if OS Specific)
 - OS: Only tested on windows

**Comment by braem** [comment]
This is because `game.cfg` is executed before the player is created: https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/gameinterface.cpp#L855 . This makes the engine think the game is *not* singleplayer. No singleplayer only cvars/commands will work there. This *should* be the case for Portal 2 as well.

Not too sure the reasoning for it to run so early. Could at least have a separate cfg that runs post entity creation a la Momentum's gamemode-specific cfgs.

Even then, `cl_portal_alternate_colors` is turned off every level spawn so that maps can use it without breaking colors for other maps. It's use needs to be rethought; I was hoping for a simple cvar that changes portal colors globally as well.

**Comment by Deepfried-Chips** [comment]
Seems to work now
