### ISSUE TITLE
Bug: Further Rocket Turret Bugs

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#677]
So, while Rocket Turrets function at their core, there's been some bugs that have cropped up with the recent fixes, here's a quick rundown:

- [x] Their Rockets will tend to explode instantly on fire, sometimes they'll break past and will properly fire.
- [ ] Rocket Turrets will not reset back to their green eye once finished firing.
- [ ] Rocket Turret animations act weirdly when the Turret gets turned off (might be an issue with the model rather than the entity?)

There's likely other bugs that I haven't documented yet.

**Comment by Luke18033** [comment]
Note that if you're spawning rocket turrets through the console, you need to use AddOutput to set a `rocketspeed` for the rockets to not get stuck, and `rocketlifetime` for them to not instantly explode.

**Comment by Luke18033** [comment]
Since the original rocket turret bugs issue was closed, I'll repost some of those here which still haven't been fixed:
- [ ] If the turret is turned off while in the "locked on" state (yellow eye), it will not visually enter that state the first time when turned back on.
- [ ] If the "rocket lifetime" expires, the turret's eye will remain red until the next time it fires (now always happens according to this issue). It should switch back to green.
- [ ] Rocket turrets tend to prefer shooting at players through portals over shooting at them directly, which isn't necessarily a bug but does seem a little odd and should probably be changed.
- [ ] If the turret is placed so that its default facing direction is anything other than +y, the extend/retract animations will break.

I'll put the suggestions in a separate issue.

**Comment by Konclan** [comment]
- [ ] Rocket turrets seem to crush the player to death more often

**Comment by Luke18033** [comment]
What do you mean crush the player?

**Comment by Konclan** [comment]
Rocket turrets can crush the player between itself and the nearest surface while they are turning around. This happened in P1 rarely, especially if you were crouched under a rocket turret on the ceiling and it looked down, but it seems like rocket turrets in P2CE are way more deadly crushing you if you're just standing next to them.

**Comment by Konclan** [comment]
Portal 1:
https://user-images.githubusercontent.com/16567080/174518187-1ccef740-a329-408e-a1f7-2bb20a07accf.mp4

P2:CE:
https://user-images.githubusercontent.com/16567080/174518209-49ef9630-1e70-4875-917e-2f9235220b1e.mp4

**Comment by Luke18033** [comment]
Should probably be changed to just bump you out like a light bridge

**Comment by Luke18033** [comment]
Opened separate issues for these. The crushing thing is probably caused by P2CE animating the collision model properly (in P1 it gets stuck in place), I still have never been able to reproduce it though, I'm not really sure why that would deal damage.
