### ISSUE TITLE
Feature: Panorama Main Menu Prototype

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#699]
### Which component should be improved?

UI/UX

### Describe your suggestion

Design and build a prototype of the panorama main menu, replacing the current placeholder menu.

This issue should be filled in with design info once that becomes available. 

### Expected result

Replacement for the current panorama main menu

**Comment by craftablescience** [comment]
Relevant images:

![P2CEMenuFirstDraft](https://user-images.githubusercontent.com/26600014/130301621-89bf7cfd-9ad9-4728-bfd2-c38223755777.png)
![unknown](https://user-images.githubusercontent.com/26600014/130301622-9fc6e043-e34c-4187-a2e5-6ce55a5fbb9d.png)
![unknown2](https://user-images.githubusercontent.com/26600014/130301624-e72f45c1-a2ac-40e1-8a59-7b77e09331fc.png)

**Comment by craftablescience** [comment]
sorry pi guy

![image](https://user-images.githubusercontent.com/26600014/130712710-4c94c0d7-ec39-4c05-bfe8-6fa6e242ba05.png)

**Comment by ozxybox** [comment]
I think this can be closed, as we currently have a prototype for the main menu? This issue seems to cover more of the same goals as https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/749 though. Does the current prototype need addon & workshop features before this can be closed?
Is this superseded by https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/885?

**Comment by AWildErin** [comment]
Yeah, this can probably be closed as we know what we want to do with the main menu

**Comment by ozxybox** [comment]
Closing this then.
