### ISSUE TITLE
Portal 2 Bug: You can't get a single portal device nor a no portal device with PotatOS.

### ISSUE THREAD

**Issue by KaziPlays** [ChaosInitiative/Portal-2-Community-Edition#775]
### Describe the bug

When you do upgrade_potatogun, it always upgrades the gun to two portals. If you use hammer however, PotatOS will simply not appear.

### To Reproduce

Method 1:

1- Open a random map;
2- Do the command give_portalgun;
3- Do the command upgrade_potatogun.

Method 2:

1- Open a map in hammer;
2- Create a weapon_portalgun entity;
3- Select only orange or only blue portals;
4- Select "Show PotatOS"
5- Run the game.

### Expected Behavior

It should just give you PotatOS, not upgrade the gun as well.

**Comment by KaziPlays** [comment]
I think the same applies to no portal portalguns

**Comment by Luke18033** [comment]
Tried the `AddPotatosToPortalgun` input on `logic_playerproxy`?

**Comment by AWildErin** [comment]
Just my take on it, I wouldn't personally call this a bug in either P2CE or Portal 2 as it's the intended effect of `upgrade_potatogun` as far as I am aware

**Comment by KaziPlays** [comment]
Nope, can try.

**Comment by Luke18033** [comment]
IIRC the "show PotatOS" keyvalue on `weapon_portalgun` doesn't work at all, which would be the real bug here.

**Comment by KaziPlays** [comment]
Hmm

**Comment by KaziPlays** [comment]
Lemme see...

**Comment by KaziPlays** [comment]
I tested it and PotatOS didn't appear.

**Comment by Luke18033** [comment]
For `upgrade_potatogun`, this is intended behavior. For the `logic_playerproxy` inputs, I can't reproduce this:
![portal2_I4vV0h4Hce](https://user-images.githubusercontent.com/19228201/146830942-1ad43be0-8fb6-41f2-a352-d5f1d7608186.png)
![portal2_6h7n9Z7rVH](https://user-images.githubusercontent.com/19228201/146830945-03f8204b-10f2-4b10-adf7-5385bc7d9c4e.png)
![portal2_93xCfQlkJt](https://user-images.githubusercontent.com/19228201/146830954-ccdc1d18-0135-4b9b-a448-bd9854a1c33d.png)
The entity keyvalue does not appear to function at all (even on a dual portalgun), which is the real bug here. I'm going to open a new issue for that since this one has gotten messy pretty fast and was reporting a different issue anyway.
