### ISSUE TITLE
Feature: add vscript paintgun and upgrade paintgun functions

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#880]
### Which component should be improved?

Other

### Describe your suggestion

just like the portalgun, there should be functions to give and upgrade your paintgun.
givePaintgun(); and upgradePaintgun();. Maybe even a command that takes a parameter for enabling and disabling what gels the gun has access to. enableGel(Int); and disableGel(Int);

**Comment by Luke18033** [comment]
Instead of a specific `GivePaintgun` function, it would probably make more sense to add a `GiveWeapon` function which takes a string for the classname of the weapon. There does still need to be a specific `UpgradePaintgun` function though, maybe we could make that generic but it probably wouldn't be useful until we have CScript...

I'd also suggest `DowngradePaintgun` which removes all gels.

**Comment by Luke18033** [comment]
Okay, here's my full suggested list:
- `GiveWeapon(string)` - gives player the specified weapon classname
- `PaintEnableAll()` - upgrade player's paint gun with all gel types
- `PaintDisableAll()` - remove all gel types from the player's paint gun
- `PaintEnable(int)` - add specified paint type to the player's paint gun
- `PaintDisable(int)` - remove specified paint type from the player's paint gun

These would all be called on the player entity itself, so in multiplayer you could individually control each player's weapons and gel types.

**Comment by JJL772** [comment]
Implemented as of 0.7.3
